language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --verbose --coverage-text
  - vendor/bin/phpcs --standard=PSR2 --extensions=php src tests
